### PR TITLE
Fix summon missing max and force flags

### LINKED ISSUE #1: Several TFS XML attributes for summons are not parsed
- [ ] Max for the individual create is not yet supported.

```xml
<summons maxSummons="2">
    <summon name="Poison Spider" interval="2000" chance="10" max="2" />
</summons>
```
- [ ] The use of the attribute “speed” which is the same as internal is not parsed.
- [ ] The “force” attribute

### PR DESCRIPTION
**Pull request by nekiro**
Also no idea why chance was in double but it was outputing 0.1 for 10, so it was wrong.
If monster has no summons they shouldnt be written to lua file.

Resolve #1

### CODE REVIEW

**Comment by soul4soul** [comment]
The `Monster` class is suppose to be a generic representation of a monster. Not necessarily specific to any OT format. In that class all percent values are stored in percentage format. So 15% is 0.15. So in this case in the TfsRevScriptSysConverter class we should multiple the summon chance by 100.

File: OTMonsterConverter/Converter/TfsRevScriptSysConverter.cs [hunk 1]
```diff
@@ -294,18 +294,33 @@ public bool WriteMonster(string directory, ref Monster monster)
...
+                if (monster.Summons.Count > 0)
                 {
-                    summon = $"	{{name = \"{monster.Summons[i].Name}\",chance = {monster.Summons[i].Chance}, interval = {monster.Summons[i].Rate}}},";
-                    if (i == monster.Summons.Count - 1)
+                    dest.WriteLine("monster.summons = {");
+                    string summon;
+                    for (int i = 0; i < monster.Summons.Count; i++)
                     {
-                        summon = summon.TrimEnd(',');
+                        summon = $"	{{name = \"{monster.Summons[i].Name}\", chance = {monster.Summons[i].Chance}, interval = {monster.Summons[i].Rate}";
```
Comment (soul4soul) [inline OTMonsterConverter/Converter/TfsRevScriptSysConverter.cs:303]: {monster.Summons[i].Chance * 100} to fix 0.10 instead of 10 bug you mentioned

File: OTMonsterConverter/Converter/TfsRevScriptSysConverter.cs [hunk 2]
```diff
@@ -294,18 +294,33 @@ public bool WriteMonster(string directory, ref Monster monster)
...
+                        } else {
+                            summon += ",";
+                        }
+                        dest.WriteLine(summon);
                     }
-                    dest.WriteLine(summon);
+                    dest.WriteLine("}");
                 }
-                dest.WriteLine("}");
                 dest.WriteLine("");
```
Comment (soul4soul) [inline OTMonsterConverter/Converter/TfsRevScriptSysConverter.cs:324]: I think your right, it makes sense to skip printing the entire summon section if there are no summons. How about moving the blank line into the conditional check too. Otherwise we would get a double blank line.

File: OTMonsterConverter/Converter/TfsXmlConverter.cs [hunk 3]
```diff
@@ -382,8 +382,10 @@ private void xmlToGeneric(TFSXmlMonster tfsMonster, out Monster monster)
                     monster.Summons.Add(new Summon()
                     {
                         Name = summon.name,
-                        Chance = (double)summon.chance / 100,
-                        Rate = (uint)((summon.interval > 0) ? summon.interval : summon.speed)
+                        Chance = (uint)Math.Min(100, summon.chance),
```
Comment (soul4soul) [inline OTMonsterConverter/Converter/TfsXmlConverter.cs:385]: `Monster` class should store percents in percentage format. How about `Chance = Math.min(1, (double)summon.chance / 100)`

File: OTMonsterConverter/MonsterTypes/Summon.cs [hunk 4]
```diff
@@ -8,6 +8,8 @@ public class Summon
     {
         public string Name { get; set; }
         public uint Rate { get; set; }
-        public double Chance { get; set; }
+        public uint Chance { get; set; }
```
Comment (soul4soul) [inline OTMonsterConverter/MonsterTypes/Summon.cs:11]: Finally leave this as a double

**Comment by soul4soul** [comment]
Thanks nekiro!
